---
- hosts: localhost
  gather_facts: True
  vars_files:
    - "{{ settings.source }}/includes/dockerapps/templates/generique/generique.yml"
  tasks:

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'traefik'
        pgerro: 'error-pages'

    - name: create traefik state
      shell: |
        echo "1" >  {{ settings.storage }}/status/{{pgrole}}

    - name: Checking for existing app data
      stat:
        path: "{{ settings.storage }}/docker/{{user.name}}/authelia/configuration.yml"
      register: check

    - name: "Set DNS Record on CloudFlare"
      include_tasks: "{{ settings.source }}/includes/config/roles/cloudflare/tasks/main.yml"
      vars:
        subdomain: "{{sub[pgrole][pgrole] if sub_enabled else pgrole}}"
      when: cloudflare_enabled

    - name: Remove {{pgrole}}
      docker_container:
        name: '{{pgrole}}'
        state: absent

    - name: Remove {{ pgerro }}
      docker_container:
        name: '{{ pgerro }}'
        state: absent

    - name: Create Basic Directories
      become: yes
      file:
        path: "{{item}}"
        state: "directory"
        mode: "0775"
        owner: "{{ lookup('env','USER') }}"
        group: "{{ lookup('env','MYGIDNAME') }}"
      with_items:
        - "{{ settings.storage }}/docker/{{pgrole}}"
        - "{{ settings.storage }}/docker/{{pgrole}}/acme"
        - "{{ settings.storage }}/docker/{{pgrole}}/rules"

    - name: Check acme.json exists
      stat:
        path: " {{ settings.storage }}/docker/{{pgrole}}/acme/acme.json"
      register: acme_json

    - name: Installing ACME (touch)
      file:
        path: "{{ settings.storage }}/docker/{{pgrole}}/acme/acme.json"
        state: touch
        mode: 0600
      when: acme_json.stat.exists == False

    - name: Create directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ settings.storage }}/docker/{{pgrole}}/"
        - "{{ settings.storage }}/docker/{{pgrole}}/rules"

    - name: create an empty file traefik.log
      file:
        path: "{{ settings.storage }}/docker/{{pgrole}}/traefik.log"
        state: touch

    - name: Import middlewares-chains.toml
      template:
        src: "{{ settings.source }}/includes/dockerapps/templates/{{pgrole}}/middlewares-chains.toml.j2"
        dest: "{{ settings.storage }}/docker/{{pgrole}}/rules/middlewares-chains.toml"

    - name: Import middlewares.toml
      template:
        src: "{{ settings.source }}/includes/dockerapps/templates/{{pgrole}}/middlewares.toml.j2"
        dest: "{{ settings.storage }}/docker/{{pgrole}}/rules/middlewares.toml"

    - name: label {{pgrole}} with cloudflare
      set_fact:
        labels:
          traefik.enable: 'true'
          ## HTTP Routers
          traefik.http.routers.traefik-rtr.entrypoints: 'http,https'
          traefik.http.routers.traefik-rtr.rule: 'Host(`{{sub[pgrole][pgrole] if sub_enabled else pgrole}}.{{user.domain}}`)'
          traefik.http.routers.traefik-rtr.tls: 'true'
          traefik.http.routers.traefik-rtr.tls.certresolver: 'letsencrypt'
          traefik.http.routers.traefik-rtr.tls.domains[0].main: '{{user.domain}}'
          traefik.http.routers.traefik-rtr.tls.domains[0].sans: '*.{{user.domain}}'
          ## Services - API
          traefik.http.routers.traefik-rtr.service: 'api@internal'
          ## Middlewares
          traefik.http.routers.traefik-rtr.middlewares: "{{ 'chain-authelia@file' if check.stat.exists and sub[pgrole].auth == 'authelia' | default(false)
            else 'chain-basic-auth@file,error-pages-middleware' if auth_enabled and sub[pgrole].auth == 'basique' | default(false)
            else 'chain-oauth@file' if auth_enabled and sub[pgrole].auth == 'oauth' | default(false)
            else 'chain-no-auth@file,error-pages-middleware' if auth_enabled and sub[pgrole].auth == 'aucune'}}"
      when: cloudflare_enabled

    - name: label traefik without cloudflare
      set_fact:
        labels:
          traefik.enable: 'true'
          ## HTTP Routers
          traefik.http.routers.traefik-rtr.entrypoints: 'http,https'
          traefik.http.routers.traefik-rtr.rule: 'Host(`{{sub[pgrole][pgrole] if sub_enabled else pgrole}}.{{user.domain}}`)'
          traefik.http.routers.traefik-rtr.tls: 'true'
          traefik.http.routers.traefik-rtr.tls.certresolver: 'letsencrypt'
          ## Services - API
          traefik.http.routers.traefik-rtr.service: 'api@internal'
          ## Middlewares
          traefik.http.routers.traefik-rtr.middlewares: "{{ 'chain-authelia@file' if check.stat.exists and sub[pgrole].auth == 'authelia' | default(false)
            else 'chain-basic-auth@file,error-pages-middleware' if auth_enabled and sub[pgrole].auth == 'basique' | default(false)
            else 'chain-oauth@file' if auth_enabled and sub[pgrole].auth == 'oauth' | default(false)
            else 'chain-no-auth@file,error-pages-middleware' if auth_enabled and sub[pgrole].auth == 'aucune'}}"
      when: not cloudflare_enabled

    - name: command traefik with cloudflare
      set_fact:
        command:
          - --global.checkNewVersion=true
          - --global.sendAnonymousUsage=true
          - --entryPoints.http.address=:80
          - --entryPoints.https.address=:443
          - --entrypoints.web.http.redirections.entrypoint.to=https
          - --entrypoints.web.http.redirections.entrypoint.scheme=https
          #- --entryPoints.traefik.address=:8080
          - --entrypoints.https.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/12,172.64.0.0/13,131.0.72.0/22
          - --api=true
          - --log=true
          - --log.level=DEBUG
          - --accessLog=true
          - --accessLog.filePath=/traefik.log
          - --accessLog.bufferingSize=100
          #- --accessLog.filters.statusCodes=400-499
          - --providers.docker=true
          - --providers.docker.endpoint=unix:///var/run/docker.sock
          - --providers.docker.exposedByDefault=false
          - --entrypoints.https.http.tls.certresolver=letsencrypt
          - --providers.docker.network=traefik_proxy
          - --providers.docker.swarmMode=false
          - --providers.file.directory=/rules
          - --providers.file.watch=true
          - --certificatesResolvers.letsencrypt.acme.email='{{cloudflare.login}}'
          - --certificatesResolvers.letsencrypt.acme.storage=/acme.json
          - --certificatesResolvers.letsencrypt.acme.dnsChallenge.provider=cloudflare
          - --certificatesResolvers.letsencrypt.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      when: cloudflare_enabled

    - name: command traefik without cloudflare
      set_fact:
        command:
          - --global.checkNewVersion=true
          - --global.sendAnonymousUsage=true
          - --entryPoints.http.address=:80
          - --entryPoints.https.address=:443
          - --entrypoints.web.http.redirections.entrypoint.to=https
          - --entrypoints.web.http.redirections.entrypoint.scheme=https
          #- --entryPoints.traefik.address=:8080
          - --api=true
          - --log=true
          - --log.level=DEBUG
          - --accessLog=true
          - --accessLog.filePath=/traefik.log
          - --accessLog.bufferingSize=100
          #- --accessLog.filters.statusCodes=400-499
          - --providers.docker=true
          - --providers.docker.endpoint=unix:///var/run/docker.sock
          - --providers.docker.exposedByDefault=false
          - --entrypoints.https.http.tls.certresolver=letsencrypt
          - --providers.docker.network=traefik_proxy
          - --providers.docker.swarmMode=false
          - --providers.file.directory=/rules
          - --providers.file.watch=true
          - --certificatesResolvers.letsencrypt.acme.email='{{user.mail}}'
          - --certificatesResolvers.letsencrypt.acme.storage=/acme.json
          - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      when: not cloudflare_enabled

    - name: Create a network
      community.docker.docker_network:
        name: traefik_proxy

    - name: Deploy Traefik
      docker_container:
        name: '{{pgrole}}'
        image: traefik:v3.0.0-beta2
        pull: yes
        published_ports:
          - "80:80"
          - "443:443"
          #- "8080:8080"
        command: '{{command}}'
        security_opts:
          - no-new-privileges:true
        env:
          CF_API_EMAIL: '{{cloudflare.login}}'
          CF_API_KEY: '{{cloudflare.api}}'
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
          - "/etc/localtime:/etc/localtime:ro"
          - "{{ settings.storage }}/docker/{{pgrole}}/acme/acme.json:/acme.json"
          - "{{ settings.storage }}/docker/{{pgrole}}/rules:/rules"
          - "{{ settings.storage }}/docker/{{pgrole}}/traefik.log:/traefik.log"
        labels: '{{labels}}'
        restart_policy: unless-stopped
        state: started
        networks:
          - name: traefik_proxy

    - name: set labels error-page
      set_fact:
        labelserror:
          traefik.enable: 'true'
          traefik.http.routers.error-pages-rtr.rule: 'HostRegexp(`{host:.+}`)'
          traefik.http.routers.error-pages-rtr.priority: '10'
          traefik.http.routers.error-pages-rtr.entrypoints: 'http,https'
          traefik.http.routers.error-pages-rtr.tls: 'true'
          traefik.http.routers.error-pages-rtr.middlewares: 'error-pages-middleware'
          traefik.http.middlewares.error-pages-middleware.errors.status: '400-599'
          traefik.http.middlewares.error-pages-middleware.errors.service: 'error-pages-svc'
          traefik.http.middlewares.error-pages-middleware.errors.query: '/{status}.html'
          traefik.http.services.error-pages-svc.loadbalancer.server.port: '8080'

    - name: Deploy tarampampam/error-pages
      docker_container:
        name: '{{ pgerro }}'
        image: tarampampam/error-pages:latest
        pull: yes
        env:
          TEMPLATE_NAME: app-down
        labels: '{{labelserror}}'
        restart_policy: unless-stopped
        state: started
        purge_networks: yes
        networks:
          - name: traefik_proxy


    - name: Google OAuth2 tasks
      include_tasks: "{{ settings.source }}/includes/dockerapps/templates/{{pgrole}}/oauth.yml"
      when: oauth_enabled

    - name: create {{pgrole}}state
      shell: |
        echo "2" >  {{ settings.storage }}/status/{{pgrole}}

    - name: create {{pgrole}}state
      shell: |
        echo "2" >  {{ settings.storage }}/status/oauth
      when: oauth_enabled

    - name: Insert traefik into database
      shell:
        cmd: |
          sqlite3 {{  settings.source }}/ssddb << EOF
              replace into applications (name,status,subdomain,port)
              values
              ('traefik',2,'{{sub[pgrole][pgrole] if sub_enabled else pgrole}}',443);
          EOF

